version: "3.9"
    
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wwwdrewtjohnsoncom
      MYSQL_DATABASE: wwwdrewtjohnsoncom
      MYSQL_USER: wwwdrewtjohnsoncom
      MYSQL_PASSWORD: wwwdrewtjohnsoncom
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wwwdrewtjohnsoncom
      WORDPRESS_DB_PASSWORD: wwwdrewtjohnsoncom
      WORDPRESS_DB_NAME: wwwdrewtjohnsoncom
volumes:
  db_data: {}
  wordpress_data: {}
